import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';

import '../../providers/tour_provider.dart';
import '../../providers/location_provider.dart';
import '../../constants/districts.dart';
import '../../models/location_model.dart';
import '../../widgets/tour_plan_card.dart';
import '../../widgets/location_card.dart';

class DistrictScreen extends StatefulWidget {
  final String districtId;

  const DistrictScreen({super.key, required this.districtId});

  @override
  State<DistrictScreen> createState() => _DistrictScreenState();
}

class _DistrictScreenState extends State<DistrictScreen> 
    with TickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 4, vsync: this);
    _loadData();
  }

  void _loadData() async {
    final tourProvider = Provider.of<TourProvider>(context, listen: false);
    final locationProvider = Provider.of<LocationProvider>(context, listen: false);
    
    await Future.wait([
      tourProvider.loadTourPlansByDistrict(widget.districtId),
      locationProvider.loadLocationsByDistrict(widget.districtId),
    ]);

    // Auto-generate tour plans if they don't exist
    _checkAndGenerateTourPlans();
  }

  void _checkAndGenerateTourPlans() async {
    final tourProvider = Provider.of<TourProvider>(context, listen: false);
    final locationProvider = Provider.of<LocationProvider>(context, listen: false);
    
    // Check if auto-generated plans already exist
    if (!tourProvider.hasAutoGeneratedPlans(widget.districtId)) {
      final touristLocations = locationProvider.getLocationsByType(LocationType.tourist);
      
      if (touristLocations.isNotEmpty) {
        await tourProvider.generateTourPlansFromLocations(
          touristLocations,
          widget.districtId,
          2, // Default 2-day tour
        );
      }
    }
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final districtName = KeralaDistricts.getDistrictName(widget.districtId);

    return Scaffold(
      appBar: AppBar(
        title: Text(districtName),
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(text: 'Tour Plans'),
            Tab(text: 'Tourist Places'),
            Tab(text: 'Restaurants'),
            Tab(text: 'Tea Spots'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _TourPlansTab(districtId: widget.districtId),
          const _LocationsTab(type: LocationType.tourist),
          const _LocationsTab(type: LocationType.restaurant),
          const _LocationsTab(type: LocationType.teaSpot),
        ],
      ),
    );
  }
}

class _TourPlansTab extends StatelessWidget {
  final String districtId;

  const _TourPlansTab({required this.districtId});

  @override
  Widget build(BuildContext context) {
    return Consumer2<TourProvider, LocationProvider>(
      builder: (context, tourProvider, locationProvider, _) {
        if (tourProvider.isLoading) {
          return const Center(child: CircularProgressIndicator());
        }

        final touristLocations = locationProvider.getLocationsByType(LocationType.tourist);

        return Column(
          children: [
            // Action buttons
            _buildActionButtons(context, tourProvider, touristLocations),
            
            // Tour plans list
            Expanded(
              child: _buildTourPlansList(context, tourProvider),
            ),
          ],
        );
      },
    );
  }

  Widget _buildActionButtons(
    BuildContext context, 
    TourProvider tourProvider, 
    List<LocationModel> touristLocations
  ) {
    return Container(
      padding: const EdgeInsets.all(16),
      child: Row(
        children: [
          Expanded(
            child: ElevatedButton.icon(
              onPressed: touristLocations.isEmpty ? null : () async {
                await tourProvider.generateTourPlansFromLocations(
                  touristLocations,
                  districtId,
                  2, // Default 2-day tour
                );
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('New tour plans generated successfully!'),
                      backgroundColor: Colors.green,
                    ),
                  );
                }
              },
              icon: const Icon(Icons.add_circle_outline),
              label: const Text('Generate Plans'),
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: ElevatedButton.icon(
              onPressed: touristLocations.isEmpty ? null : () async {
                await tourProvider.regenerateTourPlans(
                  touristLocations,
                  districtId,
                  2, // Default 2-day tour
                );
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('Tour plans regenerated successfully!'),
                      backgroundColor: Colors.blue,
                    ),
                  );
                }
              },
              icon: const Icon(Icons.refresh),
              label: const Text('Regenerate'),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.blue,
                foregroundColor: Colors.white,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTourPlansList(BuildContext context, TourProvider tourProvider) {
    if (tourProvider.error != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.error_outline,
              size: 64,
              color: Colors.red.shade300,
            ),
            const SizedBox(height: 16),
            Text(
              'Error loading tour plans',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const SizedBox(height: 8),
            Text(
              tourProvider.error!,
              style: Theme.of(context).textTheme.bodySmall,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {
                // Retry loading
                tourProvider.loadTourPlansByDistrict(districtId);
              },
              child: const Text('Retry'),
            ),
          ],
        ),
      );
    }

    if (tourProvider.tourPlans.isEmpty) {
      return const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.map_outlined,
              size: 64,
              color: Colors.grey,
            ),
            SizedBox(height: 16),
            Text(
              'No tour plans available',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.bold,
                color: Colors.grey,
              ),
            ),
            SizedBox(height: 8),
            Text(
              'Click "Generate Plans" to create automatic tour plans\nfrom the available tourist places',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.grey),
            ),
          ],
        ),
      );
    }

    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: tourProvider.tourPlans.length,
      itemBuilder: (context, index) {
        final tourPlan = tourProvider.tourPlans[index];
        return TourPlanCard(
          tourPlan: tourPlan,
          onTap: () {
            context.push('/tour/${tourPlan.id}');
          },
        );
      },
    );
  }
}

class _LocationsTab extends StatelessWidget {
  final LocationType type;

  const _LocationsTab({required this.type});

  @override
  Widget build(BuildContext context) {
    return Consumer<LocationProvider>(
      builder: (context, locationProvider, _) {
        if (locationProvider.isLoading) {
          return const Center(child: CircularProgressIndicator());
        }

        final locations = locationProvider.getLocationsByType(type);

        if (locations.isEmpty) {
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(
                  _getTypeIcon(type),
                  size: 64,
                  color: Colors.grey,
                ),
                const SizedBox(height: 16),
                Text(
                  'No ${_getTypeText(type)} available for this district',
                  style: const TextStyle(
                    fontSize: 16,
                    color: Colors.grey,
                  ),
                ),
              ],
            ),
          );
        }

        return ListView.builder(
          padding: const EdgeInsets.all(16),
          itemCount: locations.length,
          itemBuilder: (context, index) {
            final location = locations[index];
            return LocationCard(location: location);
          },
        );
      },
    );
  }

  String _getTypeText(LocationType type) {
    switch (type) {
      case LocationType.tourist:
        return 'tourist places';
      case LocationType.restaurant:
        return 'restaurants';
      case LocationType.teaSpot:
        return 'tea spots';
    }
  }

  IconData _getTypeIcon(LocationType type) {
    switch (type) {
      case LocationType.tourist:
        return Icons.place;
      case LocationType.restaurant:
        return Icons.restaurant;
      case LocationType.teaSpot:
        return Icons.local_cafe;
    }
  }
}
