import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import '../models/tour_plan_model.dart';
import '../models/location_model.dart';
import '../services/tour_plan_generator.dart';

class TourProvider extends ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  List<TourPlanModel> _tourPlans = [];
  bool _isLoading = false;
  String? _error;

  List<TourPlanModel> get tourPlans => _tourPlans;
  bool get isLoading => _isLoading;
  String? get error => _error;

  Future<void> loadTourPlansByDistrict(String district) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final query = await _firestore
          .collection('tourPlans')
          .where('district', isEqualTo: district)
          .where('isActive', isEqualTo: true)
          .orderBy('createdAt', descending: true)
          .get();

      _tourPlans = query.docs
          .map((doc) => TourPlanModel.fromMap(doc.data()))
          .toList();
    } catch (e) {
      _error = 'Error loading tour plans: $e';
      debugPrint(_error);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  TourPlanModel? getTourPlanById(String tourId) {
    try {
      return _tourPlans.firstWhere((plan) => plan.id == tourId);
    } catch (e) {
      return null;
    }
  }

  bool hasAutoGeneratedPlans(String district) {
    return _tourPlans.any((plan) => plan.district == district);
  }

  Future<void> generateTourPlansFromLocations(
    List<LocationModel> locations,
    String district,
    int duration,
  ) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final newPlans = TourPlanGenerator.generateTourPlansFromLocations(
        locations,
        district,
        duration,
      );

      // Save to Firestore
      for (final plan in newPlans) {
        await _firestore.collection('tourPlans').doc(plan.id).set(plan.toMap());
      }

      _tourPlans.addAll(newPlans);
    } catch (e) {
      _error = 'Error generating tour plans: $e';
      debugPrint(_error);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> regenerateTourPlans(
    List<LocationModel> locations,
    String district,
    int duration,
  ) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      // Remove existing plans for this district
      final existingPlans = _tourPlans.where((plan) => plan.district == district).toList();
      for (final plan in existingPlans) {
        await _firestore.collection('tourPlans').doc(plan.id).delete();
      }
      _tourPlans.removeWhere((plan) => plan.district == district);

      // Generate new plans
      await generateTourPlansFromLocations(locations, district, duration);
    } catch (e) {
      _error = 'Error regenerating tour plans: $e';
      debugPrint(_error);
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }
}
